### ISSUE TITLE
[FEATURE] Add new pet

### ISSUE THREAD

**Issue by FanyCastro** [LearningByExample/kotlin-event-driven-petstore#5]
**Describe the feature**
We have to implement the post request to add a new pet in the store.
- This feature should generate a command to perform the pet creation.

**Additional context**
https://petstore.swagger.io/#/pet/addPet

**Comment by FanyCastro** [comment]
To progress with this issue we have done this #6

**Comment by juan-medina** [comment]
We need to first complete #7 to continue this issue
